const OK_CODE = 200;
const OPTIONS_SUCCESS_STATUS = 204;
const BAD_REQUEST_CODE = 400;
const AUTH_ERROR_CODE = 401;
const ACCES_DENIED_CODE = 403;
const NOT_FOUND_ERROR_CODE = 404;
const CONFLICT_ERROR_CODE = 409;
const SERVER_ERROR_CODE = 500;
const MONGO_DB_CONFLICT_CODE = 11000;

module.exports = {
  OK_CODE,
  OPTIONS_SUCCESS_STATUS,
  BAD_REQUEST_CODE,
  AUTH_ERROR_CODE,
  ACCES_DENIED_CODE,
  NOT_FOUND_ERROR_CODE,
  CONFLICT_ERROR_CODE,
  SERVER_ERROR_CODE,
  MONGO_DB_CONFLICT_CODE,
};
